trigger:
  branches:
    include:
      - main

pool:
  name: aws_host  # Your self-hosted agent name

variables:
  - group: aws-credentials  # This variable group must contain AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY

steps:
  - script: |
      echo "Installing Terragrunt..."
      choco install terragrunt -y
    displayName: "Install Terragrunt"

  - powershell: |
      Write-Output "Configuring AWS credentials..."
      $awsDir = "$env:USERPROFILE\.aws"
      New-Item -ItemType Directory -Path $awsDir -Force | Out-Null
      $creds = "[default]`naws_access_key_id=$env:AWS_ACCESS_KEY_ID`naws_secret_access_key=$env:AWS_SECRET_ACCESS_KEY"
      $creds | Out-File -FilePath "$awsDir\credentials" -Encoding ascii
    displayName: "Configure AWS CLI credentials"

  - script: |
      cd envs/dev
      terragrunt init
      terragrunt plan
    displayName: "Terragrunt Init & Plan - dev"
