
name: terragrunt-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  paths:
    include:
      - envs/**
      - terragrunt/**
      - modules/**

pool:
  name: aws-agent

variables:
  - group: aws-credentials

stages:
- stage: Validate
  displayName: 'Lint and Format Check'
  jobs:
    - job: format_lint
      displayName: 'Check terraform fmt and tflint'
      steps:
        - script: |
            choco install terraform --version=1.6.6 -y
            choco install tflint -y
          displayName: 'Install terraform and tflint'

        - script: |
            terraform fmt -check -recursive
            if ($LASTEXITCODE -ne 0) {
              Write-Error "Terraform files are not properly formatted. Run 'terraform fmt -recursive' locally."
              exit 1
            }
          displayName: 'Check formatting with terraform fmt'
          shell: powershell

        - script: |
            tflint --recursive
          displayName: 'Lint Terraform code with tflint'

- stage: Plan
  dependsOn: Validate
  jobs:
    - job: terragruntPlan
      displayName: 'Terragrunt Init & Plan'
      steps:
        - script: |
            choco install terragrunt -y
            cd terragrunt/envs/dev
            terragrunt init
            terragrunt plan
          displayName: 'Terragrunt Init and Plan (Dev)'

- stage: Apply
  dependsOn: Plan
  condition: succeeded()
  jobs:
    - job: terragruntApply
      displayName: 'Terragrunt Apply'
      steps:
        - script: |
            cd terragrunt/envs/dev
            terragrunt apply -auto-approve
          displayName: 'Terragrunt Apply (Dev)'
