trigger:
  branches:
    include:
      - main

pool:
  name: aws_host  # Your self-hosted agent name

variables:
  - group: aws-credentials  # Loads AWS access keys

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      echo "Installing Terragrunt..."
      choco install terragrunt -y
    displayName: "Install Terragrunt"

  - script: |
      echo "Setting up AWS credentials..."
      mkdir -p ~/.aws
      echo "[default]" > ~/.aws/credentials
      echo "aws_access_key_id=$(AWS_ACCESS_KEY_ID)" >> ~/.aws/credentials
      echo "aws_secret_access_key=$(AWS_SECRET_ACCESS_KEY)" >> ~/.aws/credentials
    displayName: "Configure AWS CLI credentials"

  - script: |
      cd envs/dev
      terragrunt init
      terragrunt plan
    displayName: "Terragrunt Init & Plan - dev"

