trigger:
  batch: true
  branches:
    include:
      - main
      - feature/*
      - dev
  # Optional path filters (uncomment if you want fewer runs)
  # paths:
  #   include:
  #     - terragrunt/**
  #     - .azure/**
  #   exclude:
  #     - README.md
  #     - docs/**

pool:
  name: aws-agent

variables:
  - group: aws-credentials   # expects AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY / AWS_DEFAULT_REGION

stages:
  - stage: Format
    displayName: "Terraform Format Check"
    jobs:
      - job: FormatCheck
        displayName: "Format"
        steps:
          - checkout: self
          - script: terraform fmt -check -recursive
            displayName: "Check Terraform formatting"
            workingDirectory: '$(Build.SourcesDirectory)'

  - stage: Lint
    displayName: "Terraform Lint Check"
    dependsOn: Format
    jobs:
      - job: LintCheck
        displayName: "Lint"
        steps:
          - checkout: self
          - script: |
              tflint --init
              tflint --recursive
            displayName: "Run TFLint"
            workingDirectory: '$(Build.SourcesDirectory)'
            # If you use a custom config file, set:
            # env:
            #   TFLINT_CONFIG: $(Build.SourcesDirectory)\.tflint.hcl

  - stage: Validate
    displayName: "Terragrunt Validate"
    dependsOn: Lint
    jobs:
      - job: Validate
        displayName: "Validate (dev)"
        steps:
          - checkout: self
          - script: terragrunt run-all validate
            displayName: "Terragrunt Validate"
            workingDirectory: '$(Build.SourcesDirectory)\terragrunt\envs\dev'
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

  - stage: Plan
    displayName: "Terragrunt Plan"
    dependsOn: Validate
    jobs:
      - job: Plan
        displayName: "Plan (dev)"
        steps:
          - checkout: self
          - script: terragrunt run-all plan
            displayName: "Terragrunt Plan"
            workingDirectory: '$(Build.SourcesDirectory)\terragrunt\envs\dev'
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

  - stage: Apply
    displayName: "Terragrunt Apply"
    dependsOn: Plan
    # Only allow manual applies from the Run button
    condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
    jobs:
      - job: Apply
        displayName: "Apply (dev)"
        steps:
          - checkout: self
          - script: terragrunt run-all apply -auto-approve
            displayName: "Terragrunt Apply"
            workingDirectory: '$(Build.SourcesDirectory)\terragrunt\envs\dev'
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
