trigger:
  batch: true
  branches:
    include:
      - main
      - feature/*
      - dev
  # Optional path filters:
  # paths:
  #   include:
  #     - terragrunt/**
  #     - .azure/**
  #   exclude:
  #     - README.md
  #     - docs/**

pool:
  name: aws-agent

variables:
  - group: aws-credentials   # expects AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY / AWS_DEFAULT_REGION

stages:
  - stage: Format
    displayName: "Terraform Format Check"
    jobs:
      - job: FormatCheck
        displayName: "Format"
        steps:
          - checkout: self
          - script: terraform fmt -check -recursive
            displayName: "Check Terraform formatting"
            workingDirectory: '$(Pipeline.Workspace)\s'

  - stage: Lint
    displayName: "Terraform Lint Check"
    dependsOn: Format
    jobs:
      - job: LintCheck
        displayName: "Lint"
        steps:
          - checkout: self
          - script: |
              tflint --init
              tflint --recursive
            displayName: "Run TFLint"
            workingDirectory: '$(Pipeline.Workspace)\s'
            # If you use a custom config file, set:
            # env:
            #   TFLINT_CONFIG: $(Pipeline.Workspace)\s\.tflint.hcl

  - stage: Validate
    displayName: "Terragrunt Validate"
    dependsOn: Lint
    jobs:
      - job: Validate
        displayName: "Validate (dev)"
        steps:
          - checkout: self

          # Optional: keep this once to confirm paths resolve correctly
          - script: |
              echo Pipeline.Workspace = $(Pipeline.Workspace)
              echo Build.SourcesDirectory = $(Build.SourcesDirectory)
              if exist "$(Pipeline.Workspace)\s" (echo Repo folder exists) else (echo Repo folder MISSING)
              dir "$(Pipeline.Workspace)\s\terragrunt\envs\dev"
            displayName: "Debug paths"

          - script: terragrunt run-all validate
            displayName: "Terragrunt Validate"
            workingDirectory: '$(Pipeline.Workspace)\s\terragrunt\envs\dev'
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

  - stage: Plan
    displayName: "Terragrunt Plan"
    dependsOn: Validate
    jobs:
      - job: Plan
        displayName: "Plan (dev)"
        steps:
          - checkout: self
          - script: terragrunt run-all plan
            displayName: "Terragrunt Plan"
            workingDirectory: '$(Pipeline.Workspace)\s\terragrunt\envs\dev'
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

  - stage: Apply
    displayName: "Terragrunt Apply"
    dependsOn: Plan
    # Only allow manual applies from the Run button
    condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
    jobs:
      - job: Apply
        displayName: "Apply (dev)"
        steps:
          - checkout: self
          - script: terragrunt run-all apply -auto-approve
            displayName: "Terragrunt Apply"
            workingDirectory: '$(Pipeline.Workspace)\s\terragrunt\envs\dev'
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
