name: terragrunt-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  paths:
    include:
      - envs/**
      - modules/**
      - .tflint.hcl
      - azure-pipelines.yml

pool:
  name: aws-agent  # <- your self-hosted agent pool

variables:
  - group: aws-credentials  # contains AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY / AWS_DEFAULT_REGION (optional)

stages:
- stage: Validate
  displayName: 'Lint and Format Check'
  jobs:
    - job: format_lint
      displayName: 'Check terraform fmt and tflint'
      steps:
        - script: |
            choco upgrade terraform --version=1.9.5 --allow-downgrade -y
            choco install tflint -y
          displayName: 'Install Terraform and tflint'

        - task: PowerShell@2
          displayName: 'Check formatting with terraform fmt'
          inputs:
            targetType: 'inline'
            script: |
              terraform version
              terraform fmt -check -recursive
              if ($LASTEXITCODE -ne 0) {
                Write-Error "Terraform files are not properly formatted. Run 'terraform fmt -recursive' locally."
                exit 1
              }

        - script: |
            if exist .tflint.hcl (
              tflint --init
            )
            tflint --recursive
          displayName: 'Lint Terraform code with tflint'

- stage: Plan
  dependsOn: Validate
  displayName: 'Terragrunt Plan (Dev)'
  jobs:
    - job: terragruntPlan
      displayName: 'Terragrunt Init & Plan (Dev)'
      steps:
        - script: |
            choco install terragrunt -y
            cd envs/dev
            terragrunt --version
            terragrunt init -reconfigure
            terragrunt plan -input=false
          displayName: 'Terragrunt Init and Plan (Dev)'

- stage: Apply
  dependsOn: Plan
  condition: succeeded()
  displayName: 'Terragrunt Apply (Dev)'
  jobs:
    - job: terragruntApply
      displayName: 'Terragrunt Apply (Dev)'
      steps:
        - script: |
            cd envs/dev
            terragrunt apply -auto-approve -input=false
          displayName: 'Terragrunt Apply (Dev)'
